### ISSUE TITLE
Error exporting page that contains xml with CDATA parts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [moxter/mxupdate-archive#128]
```
What steps will reproduce the problem?
1. in busines-modeller, create a page admin object as follows:
Name: MyTest
Description: My Test
Mime Type: text/xml
Content:
<?xml version="1.0" encoding="ISO-8859-1"?>
<MyConfig>
    <Select><![CDATA[attribute[$<attribute_MyAttribute>]]]></Select>
</MyConfig>

2. in the MQL (RMI)-Console execute:
exec prog MxUpdate -e --path "<YOUR_SCHEMA_ROOT_DIR>" --page "MyTest";
(Replace the <YOUR_SCHEMA_ROOT_DIR> with a path convenient on your system)

What is the expected output? What do you see instead?
Expected:
The PAGE file will be created and contains the page configuration

Instead:
export page 'MyTest'
[Fatal Error] :25:62: The element type "pageContent" must be terminated by 
the matching end-tag "</pageContent>".
org.xml.sax.SAXParseException: The element type "pageContent" must be 
terminated by the matching end-tag "</pageContent>".
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at 
org.mxupdate.update.AbstractAdminObject_mxJPOMQXqtQAAAAEAAAAo.parse(A
bstractAdminObject_mxJPOMQXqtQAAAAEAAAAo.java:278)
        at org.mxupdate.update.AbstractObject_mxJPOlxNxfgAAAAEAAAAg.export
(AbstractObject_mxJPOlxNxfgAAAAEAAAAg.java:184)
        at MxUpdate_mxJPOz701pgAAAAEAAAAl.export
(MxUpdate_mxJPOz701pgAAAAEAAAAl.java:613)
        at MxUpdate_mxJPOz701pgAAAAEAAAAl.mxMain
(MxUpdate_mxJPOz701pgAAAAEAAAAl.java:469)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at matrix.db.JPOSupport.invokeObject(JPOSupport.java:125)
Error: #1900068: exec program failed
System Error: #5000001: org.xml.sax.SAXParseException: The element 
type "pageContent" must be terminated by the matching end-
tag "</pageContent>".


What version of the product are you using? On what operating system?
MxUpdate v0.9.0 on Windows XP with Matrix v6r2009HF57

Please provide any additional information below.
I think it is related to the CDATA parts as the mx build-in export, if 
used with the xml option, itself contains the content of the page in and 
CDATA part. The so resulting nested CDATA in CDATA might confuse the 
parsing within MxUpdate if it uses the mx export command to get the page 
data.


```

Original issue reported on code.google.com by `marcus.b...@sonyericsson.com` on 2 Jun 2010 at 1:11

**Comment by GoogleCodeExporter** [comment]
```
Meanwhile I did a quick hack by changing the Page JPO to use URLEncoder in an 
overwritten execXMLExport(ParameterCache):
- get the content between "<pageContent><![CDATA[" and "]]></pageContent>"
- if it is xml
-- URLEncode it
-- replace it in the xml
-- set flag to indicate encoding
And change method writeEnd(ParameterCache_mxJPO, Appendable) to use URLDecoder 
if that flag is set.

```

Original comment by `marcus.b...@sonyericsson.com` on 10 Jun 2010 at 3:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 7 Feb 2014 at 8:31
- Added labels: **MigrationStatus-New**
