### ISSUE TITLE
0.10.0 not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [moxter/mxupdate-archive#161]
```
What steps will reproduce the problem?
1. Eclipse Helios SR2 64 bit windows installation
2. v. 0.10.0 Eclipse plugin installation via Eclipse using 
http://mxupdate.googlecode.com/svn/mxupdate-eclipse-site/tags/
3. I copied eMatrixServletRMI_2012.0.0.jar to eclipse\plugins dir. The same 
file is working with v. 0.9.0
4. I install MxUpdate JPOs with mql
4. I created a new java project, then I used import command and within dialog 
"Define the Project for the Connection from where to Import" I choosed the new 
project then I press the Next button but nothing happens.
The eclipse .log file contains:
!ENTRY org.eclipse.ui 4 0 2011-11-11 13:52:30.203
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
    at org.mxupdate.eclipse.importwizard.Step3ConfigurationItemsPage.setVisible(Step3ConfigurationItemsPage.java:140)
    at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1239)
    at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1218)
    at org.eclipse.jface.wizard.WizardDialog$6.run(WizardDialog.java:1207)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1205)
    at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:894)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:426)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4066)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3657)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:147)
    at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:274)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:293)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:476)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
    at org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
    at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:157)
    at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:171)
    at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:97)
    at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:168)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4066)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3657)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2640)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2604)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2438)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:671)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:664)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:115)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1408)


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
0.10.0 windows 64 bit

Please provide any additional information below.

```

Original issue reported on code.google.com by `Stefano....@gmail.com` on 11 Nov 2011 at 12:57

Attachments:
- [.log](https://storage.googleapis.com/google-code-attachments/mxupdate/issue-161/comment-0/.log)

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 24 Sep 2013 at 9:07
- Added labels: **Component-Plugin**
- Removed labels: **Component-Update**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 7 Feb 2014 at 8:18
- Changed state: **PluginNew**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 7 Feb 2014 at 9:41
- Added labels: **MigrationStatus-New**
