### ISSUE TITLE
Not able connect to Enovia 2012x version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [moxter/mxupdate-archive#172]
```
What steps will reproduce the problem?
1. Connect to Enovia from Eclipse

What is the expected output? What do you see instead?
Successful connection 

What version of the product are you using? On what operating system?
Version: Juno Service Release 1
Build id: 20121004-1855

Please provide any additional information below.
Enovia version 2012x
```

Original issue reported on code.google.com by `sandeepk...@gmail.com` on 27 Nov 2012 at 3:38

**Comment by GoogleCodeExporter** [comment]
```
Error Message
java.lang.Exception: Expected "tenant", got "user" on line 8
    at com.matrixone.jdl.MatrixXMLSerializable.decodeStart(MatrixXMLSerializable.java:510)
    at com.matrixone.jdl.MatrixXMLSerializable.parseString(MatrixXMLSerializable.java:480)
    at com.matrixone.jdl.MatrixXMLSerializable.decodeString(MatrixXMLSerializable.java:521)
    at com.matrixone.jdl.MatrixXMLDispatch.dispatch_bosContext(MatrixXMLDispatch.java:1050)
    at com.matrixone.jdl.MatrixXMLDispatch.dispatch(MatrixXMLDispatch.java:74)
    at com.matrixone.servlet.MatrixXMLServlet.doPost(MatrixXMLServlet.java:196)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Unknown Source)

```

Original comment by `sandeepk...@gmail.com` on 27 Nov 2012 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
Hello,
Did you ever figure out the cause of this issue?  I have a similar one.

Thanks
Mike
michael.crema@baesystems.com
```

Original comment by `mcre...@gmail.com` on 19 Dec 2012 at 1:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 24 Sep 2013 at 9:03
- Added labels: **Component-Plugin**
- Removed labels: **Component-Update**

**Comment by GoogleCodeExporter** [comment]
```
This error happens if an eMatrixServletRMI.jar library from a older MX is used. 
The user version of the jar library must fit exact (to used from the installed 
MX server application).
```

Original comment by `tim.mox...@innobix.com` on 25 Sep 2013 at 9:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 7 Feb 2014 at 8:18
- Changed state: **PluginNew**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tim.mox...@innobix.com` on 7 Feb 2014 at 9:41
- Added labels: **MigrationStatus-New**

**Comment by GoogleCodeExporter** [comment]
```
thnx 
```

Original comment by `pradeepr...@gmail.com` on 15 May 2014 at 12:01
